# Generated by Django 6.0.3 on 2026-04-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField(max_length=20)),
                ('y_coordinate', models.IntegerField(default=10, editable=False)),
                ('x_coordinate', models.IntegerField(default=0, unique=True)),
            ],
        ),
    ]
