# Generated by Django 6.0.4 on 2026-06-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0008_location_stair_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('date_pub', models.DateTimeField(auto_now=True)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='Map.location')),
            ],
        ),
    ]
