# Generated by Django 6.0.4 on 2026-06-13 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0009_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_destination', to='Map.location'),
        ),
    ]
