# Generated by Django 6.0.4 on 2026-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0010_announcement_from_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user-reports/%Y/%m/%d/')),
                ('uploade_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
