# Generated by Django 6.0.4 on 2026-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0011_hazardreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='room_name',
            field=models.TextField(max_length=100),
        ),
    ]
