# Generated by Django 6.0.4 on 2026-06-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0012_alter_location_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
