# Generated by Django 6.0.4 on 2026-06-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0013_connection_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
